version: '3.3'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rest
    ports:
      - 5432:5432
    volumes:
      - restpsql:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: postgres_adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  restpsql:
    external: true